language: node_js

node_js:
  - "8"
  - "10"
  - "lts/*"

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      before_script: npm run lint
      script: npm run test:coverage
      after_script: cat ./coverage/lcov.info | npx coveralls

    - stage: deploy
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: pwd # npx semantic-release